import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const catalog=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8'));
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin='https://rakesh3834.github.io/gokurious-class3/';
const repo='https://github.com/rakesh3834/gokurious-class3';
const head=(title,description,prefix='',canonical='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(description)}"><title>${esc(title)} | GoKurious Class 3</title><link rel="stylesheet" href="${prefix}assets/portal.css">${canonical?`<link rel="canonical" href="${origin}${canonical}">`:''}<meta name="theme-color" content="#4338ca"></head>`;
const brand=(prefix='')=>`<a class="brand" href="${prefix}index.html" aria-label="GoKurious — all subjects">Go<span>Kurious</span></a>`;
const header=(prefix='')=>`<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="shell header-row">${brand(prefix)}<span class="class-label">Class 3</span></div></header>`;
const footer=(prefix='')=>`<footer class="site-footer"><div class="shell footer-row"><span>GoKurious · Class 3 · 100 interactive lessons</span><a href="${prefix}index.html">All subjects</a></div></footer>`;
const theme=s=>`--subject:${s.color};--soft:${s.soft}`;
const draftNote=`<aside class="notice" aria-label="Hindi audio review"><p><strong>Hindi audio is a preview.</strong> All 20 lessons are available. Pronunciation review is pending; a grown-up can help check the sounds.</p><p lang="hi">हिन्दी ऑडियो के उच्चारण की समीक्षा बाकी है। ध्वनियाँ सुनते समय किसी बड़े की मदद लें।</p></aside>`;
const write=async(file,html)=>{const p=path.join(root,file);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,html+'\n');};
assert.equal(catalog.subjects.length,5);
let total=0;
for(const s of catalog.subjects){assert.equal(s.lessons.length,20);for(const l of s.lessons){const b=await fs.readFile(path.join(root,'content',s.slug,l.id+'.html'));assert.equal(crypto.createHash('sha256').update(b).digest('hex'),l.sha256);assert.equal(b.length,l.bytes);total++;}}
assert.equal(total,100);
await write('index.html',head('Choose a subject','Explore 100 interactive Class 3 lessons in Science, Maths, English, Hindi and Computer.','','')+`<body>${header()}<main id="main" class="shell"><section class="intro"><p class="eyebrow">Learn by doing</p><h1>What will you explore today?</h1><p class="lede">Explore a little world. Change something. See what happens. Discover 100 hands-on lessons in five subjects.</p></section><section aria-labelledby="subjects-title"><div class="section-row"><h2 id="subjects-title">Your subjects</h2><p>5 subjects · 100 lessons</p></div><ul class="subject-grid">${catalog.subjects.map(s=>`<li><a class="subject-card" style="${theme(s)}" href="subjects/${s.slug}/index.html"><div class="subject-top"><span class="subject-no">${s.number}</span><span class="count">20 lessons</span></div><img class="subject-preview" src="assets/previews/${s.lessons[0].id}.png" alt="" loading="lazy"><h3>${s.name==='Hindi'?'<span lang="hi">हिन्दी</span> · Hindi':esc(s.name)}</h3><p${s.slug==='hindi'?' lang="hi"':''}>${esc(s.description)}</p><span class="open-label">Explore ${esc(s.name)}<span class="arrow" aria-hidden="true">↗</span></span>${s.slug==='hindi'?'<span class="review-tag">Audio pronunciation review pending</span>':''}</a></li>`).join('')}</ul></section></main>${footer()}</body></html>`);
for(const s of catalog.subjects){
 const nav=`<nav aria-label="Subjects"><ul class="subject-links">${catalog.subjects.map(x=>`<li><a href="../${x.slug}/index.html"${x.slug===s.slug?' aria-current="page"':''}>${esc(x.name)}</a></li>`).join('')}</ul></nav>`;
 await write(`subjects/${s.slug}/index.html`,head(s.name+' lessons',`20 interactive Class 3 ${s.name} lessons with activities, explanations and challenges.`,'../../',`subjects/${s.slug}/`)+`<body style="${theme(s)}">${header('../../')}<main id="main" class="shell"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="../../index.html">All subjects</a><span aria-hidden="true">/</span><span>${esc(s.name)}</span></nav><section class="intro subject-intro"><p class="eyebrow">Class 3 · 20 lessons</p><h1>${s.name==='Hindi'?'<span lang="hi">हिन्दी</span> · Hindi':esc(s.name)}</h1><p class="lede"${s.slug==='hindi'?' lang="hi"':''}>${esc(s.description)}</p></section>${nav}${s.slug==='hindi'?draftNote:''}<section aria-labelledby="lessons-title"><div class="section-row"><h2 id="lessons-title">Choose a lesson</h2><p>Explore at your own pace</p></div><label class="topic-search">Find a topic<input type="search" id="topic-search" placeholder="Search by topic, title or ID" autocomplete="off"></label><p id="search-result" role="status"></p><ol class="lesson-grid">${s.lessons.map((l,i)=>`<li><a class="lesson-card" href="../../content/${s.slug}/${l.id}.html"><img class="lesson-preview" src="../../assets/previews/${l.id}.png" alt="" loading="lazy"><div class="lesson-meta"><span class="lesson-order">Lesson ${String(i+1).padStart(2,'0')}</span><span>${l.minutes} min</span></div><h3 lang="${l.language}">${esc(l.title)}</h3><p lang="${l.language}">${esc(l.topic)}</p><span class="open-label">Open lesson <span class="lesson-id">${l.id} <span aria-hidden="true">↗</span></span></span></a></li>`).join('')}</ol></section><p class="page-bottom"><a class="back-link" href="../../index.html">← All subjects</a></p></main>${footer('../../')}<script src="../../assets/search.js" defer></script></body></html>`);
 for(const [i,l] of s.lessons.entries()){
  const prev=i?`<a class="page-control" href="${s.lessons[i-1].id}.html" aria-label="Previous lesson: ${esc(s.lessons[i-1].title)}">← Previous</a>`:'<span class="page-control" aria-disabled="true">← Previous</span>';
  const next=i<19?`<a class="page-control" href="${s.lessons[i+1].id}.html" aria-label="Next lesson: ${esc(s.lessons[i+1].title)}">Next →</a>`:`<a class="page-control" href="../../subjects/${s.slug}/index.html">All lessons →</a>`;
  const content=`../../content/${s.slug}/${l.id}.html`;
  await write(`lessons/${s.slug}/${l.id}.html`,head(l.title,l.topic,'../../',`content/${s.slug}/${l.id}.html`).replace('</head>',`<meta http-equiv="refresh" content="0; url=${content}"></head>`)+`<body><main class="empty"><h1>${esc(l.title)}</h1><p>This lesson now opens directly in the learning studio.</p><a href="${content}">Open the interactive lesson →</a><nav>${prev}${next}</nav>${s.slug==='hindi'?draftNote:''}</main><script>location.replace(${JSON.stringify(content)});</script></body></html>`);
 }
}
await write('404.html',head('Page not found','Return to the GoKurious Class 3 subjects.','/gokurious-class3/')+`<body><main class="empty"><p class="eyebrow">GoKurious · Class 3</p><h1>Let’s find your lesson.</h1><p>This address does not match a lesson. Choose a subject to start exploring.</p><a class="back-link" href="/gokurious-class3/">← All subjects</a></main></body></html>`);
console.log(`Built subject portal: 5 subjects, ${total} lesson redirects. Updated content hashes verified.`);
